server:
  port: 8080
# 热部署生效
spring:
  devtools:
    restart:
      enabled: true
      # 设置监听重启目录  spring.devtools.restart.additional-paths：src/main/java
      # 设置不监听重启目录 spring.devtools.restart.exclude: static / **，public / **
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.14.161.16/demo?charactEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    database: MYSQL
    show-sql: true
    hibernate: org.hibernate.cfg.ImprovedNamingStrategy
    name: druid
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM t_user
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      # spring.datasource.druid.useGlobalDataSourceStat=true
  # redis配置
  redis:
    host: 106.14.161.16
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 30000
  jpa:
    properties:
          hibernate.format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: true
  # ES集群配置
  elasticsearch:
    bboss:
        dslfile:
            refreshInterval: -1
        elasticPassword: changeme
        elasticUser: elastic
        elasticsearch:
            dateFormat: yyyy.MM.dd
            discoverHost: false
            rest:
              hostNames: 10.21.20.168:9200
            showTemplate: true
            timeZone: Asia/Shanghai
            ttl: 2.0
        http:
            connectionRequestTimeout: 400000
            defaultMaxPerRoute: 200
            hostnameVerifier: ''
            keepAlive: 3600000
            keyPassword: ''
            keystore: ''
            maxHeaderCount: 200
            maxLineLength: -1
            maxTotal: 400
            retryTime: 1
            soKeepAlive: false
            soReuseAddress: false
            timeToLive: 3600000
            timeoutConnection: 400000
            timeoutSocket: 400000

# 设置logger打印控制台jpa sql语句
logging:
  level:
    com.kedacom.repository: trace